### ISSUE TITLE
Welcome problem 

### ISSUE THREAD

**Issue by SeaworldLuna** [SeaWorldMC/Issue-Tracker#6]
When people join for the first time they get the welcome message as always. But once you leave and rejoin the same welcome message pops up. -Luna🐳🐬

**Comment by MakingMiners** [comment]
Should be a easy fix, Saw that today!  Thank you for reporting it! 

-Director of Development,
 MakingMiners

**Comment by Arl006** [comment]
Simple fix with SWMC-Core.
